version: '3.8'
services:
  server:
      image: node:16
      container_name: server_auth_facebook
      ports:
        - 5000:3000
      build:
        context: .
        dockerfile: Dockerfile
      command: npm run start:dev

  database:
    image: postgres:13
    container_name: tyba_database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PG_PORT}:80
    depends_on:
      - database